---
repos:
- repo: https://github.com/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: end-of-line-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: lint # Running locally to give pylint access to imports
    name: Python linting
    types: [python]
    language: system
    entry: flake8 Flask-App && bandit -r --exclude=node_modules Flask-App
